# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/konstantinos/Documents/University/7th_Semester/Parallel_and_Disturbuted_Systems/Project3(Game Of Life)/game_of_life"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/konstantinos/Documents/University/7th_Semester/Parallel_and_Disturbuted_Systems/Project3(Game Of Life)/game_of_life"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/konstantinos/Documents/University/7th_Semester/Parallel_and_Disturbuted_Systems/Project3(Game Of Life)/game_of_life/CMakeFiles" "/home/konstantinos/Documents/University/7th_Semester/Parallel_and_Disturbuted_Systems/Project3(Game Of Life)/game_of_life/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/konstantinos/Documents/University/7th_Semester/Parallel_and_Disturbuted_Systems/Project3(Game Of Life)/game_of_life/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game_of_life.exe

# Build rule for target.
game_of_life.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_of_life.exe
.PHONY : game_of_life.exe

# fast build rule for target.
game_of_life.exe/fast:
	$(MAKE) -f CMakeFiles/game_of_life.exe.dir/build.make CMakeFiles/game_of_life.exe.dir/build
.PHONY : game_of_life.exe/fast

#=============================================================================
# Target rules for targets named game_of_life_serial

# Build rule for target.
game_of_life_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_of_life_serial
.PHONY : game_of_life_serial

# fast build rule for target.
game_of_life_serial/fast:
	$(MAKE) -f CMakeFiles/game_of_life_serial.dir/build.make CMakeFiles/game_of_life_serial.dir/build
.PHONY : game_of_life_serial/fast

#=============================================================================
# Target rules for targets named game_of_life_serial_lib

# Build rule for target.
game_of_life_serial_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_of_life_serial_lib
.PHONY : game_of_life_serial_lib

# fast build rule for target.
game_of_life_serial_lib/fast:
	$(MAKE) -f CMakeFiles/game_of_life_serial_lib.dir/build.make CMakeFiles/game_of_life_serial_lib.dir/build
.PHONY : game_of_life_serial_lib/fast

#=============================================================================
# Target rules for targets named game_of_life_utils

# Build rule for target.
game_of_life_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_of_life_utils
.PHONY : game_of_life_utils

# fast build rule for target.
game_of_life_utils/fast:
	$(MAKE) -f CMakeFiles/game_of_life_utils.dir/build.make CMakeFiles/game_of_life_utils.dir/build
.PHONY : game_of_life_utils/fast

src/game_of_life.o: src/game_of_life.cpp.o
.PHONY : src/game_of_life.o

# target to build an object file
src/game_of_life.cpp.o:
	$(MAKE) -f CMakeFiles/game_of_life_serial_lib.dir/build.make CMakeFiles/game_of_life_serial_lib.dir/src/game_of_life.cpp.o
.PHONY : src/game_of_life.cpp.o

src/game_of_life.i: src/game_of_life.cpp.i
.PHONY : src/game_of_life.i

# target to preprocess a source file
src/game_of_life.cpp.i:
	$(MAKE) -f CMakeFiles/game_of_life_serial_lib.dir/build.make CMakeFiles/game_of_life_serial_lib.dir/src/game_of_life.cpp.i
.PHONY : src/game_of_life.cpp.i

src/game_of_life.s: src/game_of_life.cpp.s
.PHONY : src/game_of_life.s

# target to generate assembly for a file
src/game_of_life.cpp.s:
	$(MAKE) -f CMakeFiles/game_of_life_serial_lib.dir/build.make CMakeFiles/game_of_life_serial_lib.dir/src/game_of_life.cpp.s
.PHONY : src/game_of_life.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/game_of_life.exe.dir/build.make CMakeFiles/game_of_life.exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/game_of_life.exe.dir/build.make CMakeFiles/game_of_life.exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/game_of_life.exe.dir/build.make CMakeFiles/game_of_life.exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/serial.o: src/serial.cpp.o
.PHONY : src/serial.o

# target to build an object file
src/serial.cpp.o:
	$(MAKE) -f CMakeFiles/game_of_life_serial.dir/build.make CMakeFiles/game_of_life_serial.dir/src/serial.cpp.o
.PHONY : src/serial.cpp.o

src/serial.i: src/serial.cpp.i
.PHONY : src/serial.i

# target to preprocess a source file
src/serial.cpp.i:
	$(MAKE) -f CMakeFiles/game_of_life_serial.dir/build.make CMakeFiles/game_of_life_serial.dir/src/serial.cpp.i
.PHONY : src/serial.cpp.i

src/serial.s: src/serial.cpp.s
.PHONY : src/serial.s

# target to generate assembly for a file
src/serial.cpp.s:
	$(MAKE) -f CMakeFiles/game_of_life_serial.dir/build.make CMakeFiles/game_of_life_serial.dir/src/serial.cpp.s
.PHONY : src/serial.cpp.s

src/utilities.o: src/utilities.cpp.o
.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/game_of_life_utils.dir/build.make CMakeFiles/game_of_life_utils.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i
.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/game_of_life_utils.dir/build.make CMakeFiles/game_of_life_utils.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s
.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/game_of_life_utils.dir/build.make CMakeFiles/game_of_life_utils.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... game_of_life.exe"
	@echo "... game_of_life_serial"
	@echo "... game_of_life_serial_lib"
	@echo "... game_of_life_utils"
	@echo "... rebuild_cache"
	@echo "... src/game_of_life.o"
	@echo "... src/game_of_life.i"
	@echo "... src/game_of_life.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/serial.o"
	@echo "... src/serial.i"
	@echo "... src/serial.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

